version: "3.4"

services:
  frontend:
    image: node:18.16-alpine
    container_name: frontend
    entrypoint: ./entrypoint.sh
    ports:
      - 5173:5173
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
